function catchError (error) {
  throw new Error(error);
}

export { catchError };